### ISSUE TITLE
apt-get not working on Mac

### ISSUE THREAD

**Issue by apoikola** [evernym/anoncreds#4] opened 2016-10-11 16:29 UTC
I tried:

`git clone https://github.com/evernym/anoncreds.git`

`sh setup-charm.sh`

and got

> sudo: apt-get: command not found

Should there be a Mac flavor of the script or am I missing something?

**Comment by dhh1128** [comment] 2016-10-11 16:40
Yes, we need to modify the .sh file to support mac. In the meantime, you can manually do the steps in setup-charm.sh; I wrote about them in this related issue: https://github.com/sovrin-foundation/sovrin/issues/7

**Comment by rufftimothy** [comment] 2016-10-11 16:42
Maybe a good Q and A for the forum?

Timothy Ruff
CEO, Evernym, Inc.
timothy.ruff@evernym.com
evernym.com <http://www.evernym.com/>
LinkedIn <http://www.linkedin.com/in/rufftim/>

<http://www.linkedin.com/in/rufftim/>

**Comment by apoikola** [comment] 2016-10-13 20:12
I replaced the apt-get in the beginning of the script with home brew versions + install wget.

`brew install flex`
`brew install bison`
`brew install openssl`
`brew install gmp`
`brew install wget`

That got me quite far but not quit until the end...

> building 'charm.core.math.pairing' extension
/usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -DBENCHMARK_ENABLED=1 -Icharm/core/utilities/ -Icharm/core/benchmark/ -I/usr/local/include -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c charm/core/math/pairing/pairingmodule.c -o build/temp.macosx-10.6-intel-3.5/charm/core/math/pairing/pairingmodule.o
In file included from charm/core/math/pairing/pairingmodule.c:30:
charm/core/math/pairing/pairingmodule.h:44:10: fatal error: 'openssl/objects.h'
      file not found
#include "openssl/objects.h"

**Comment by jasonalaw** [comment] 2016-10-14 03:51
Antti:

I'm sorry I've been slow to respond. I do have this issue on my radar, but
I've been traveling for the past 48 hours with little access to code or the
internet. I'm hoping I can dig deeper tomorrow.

**Comment by howardkitto** [comment] 2016-10-14 14:49
I have the same openssl issue, here is some env information that might help:

$ brew install gmp
Warning: gmp-6.1.1 already installed
$ brew install pbc
Warning: pbc-0.5.14 already installed
$ brew install libsodium
Warning: libsodium-1.0.11 already installed

$ make
Setup build/staging directories
set -x
set +x
Building the Charm Framework
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 setup.py build  build_ext -L/usr/local/lib -I/usr/local/include 
Platform: Darwin
Config file: /Users/howardkitto/Projects/sovrin/charm-dev/config.mk
running build
running build_py
copying charm/config.py -> build/lib.macosx-10.6-intel-3.5/charm
package init file 'charm/schemes/prenc/__init__.py' not found (or not a regular file)
running build_ext
building 'charm.core.math.pairing' extension
/usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -DBENCHMARK_ENABLED=1 -Icharm/core/utilities/ -Icharm/core/benchmark/ -I/usr/local/include -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c charm/core/math/pairing/pairingmodule.c -o build/temp.macosx-10.6-intel-3.5/charm/core/math/pairing/pairingmodule.o
In file included from charm/core/math/pairing/pairingmodule.c:30:
charm/core/math/pairing/pairingmodule.h:44:10: fatal error: 'openssl/objects.h' file not found
#include "openssl/objects.h"
         ^
1 error generated.
error: command '/usr/bin/clang' failed with exit status 1
make: *** [all] Error 1


$ sudo pip3 install sovrin
...
In file included from charm/core/math/pairing/pairingmodule.c:30:
    charm/core/math/pairing/pairingmodule.h:37:10: fatal error: 'gmp.h' file not found
    #include <gmp.h>
             ^
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1

**Comment by dhh1128** [comment] 2016-10-15 05:00
The openssl issue is caused by Apple changing how openssl installs on OSX. The solution that worked for me is documented here: https://solitum.net/openssl-os-x-el-capitan-and-brew/ (and here: http://stackoverflow.com/questions/32960032/nginx-cannot-find-openssl-development-headers)

**Comment by apoikola** [comment] 2016-10-17 13:48
Thanks @dhh1128 that solved the problem at least for me... I shared the script and README update in the pull request.

**Comment by dhh1128** [comment] 2016-10-17 16:41
Thanks for the pull request, @apoikola ! I believe we're working now, so I'm going to close the issue. We can reopen it if we need to.

**Closed by dhh1128** 2016-10-17 16:41 UTC
